### ISSUE TITLE
How to use this on already blurry images?

### ISSUE THREAD

**Issue by luuude** [Marien-RENAUD/SNORE#2]
You code generates the blur, how can I try this on naturally blured images?

**Comment by Marien-RENAUD** [comment]
This code has been developed for Plug-and-Play (PnP) methods that requiere to have blur kernel (see the paper : https://arxiv.org/abs/2402.01779 for more details). For your natural images, you need to put the appropriate blur  kernel in the algorithm to use it.

To restore an image with an unknown kernel of blur is a challenging question, named blind deblurring (or blind inverse problem). In the PnP literature, there is a few try to extend that kind of technique for blind deblurring, see for instance : https://proceedings.neurips.cc/paper_files/paper/2023/hash/f810c2ba07bae78dfe9d25c5d40c5536-Abstract-Conference.html.
